services:
  robot-automation:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: robot-automation

    user: "1000:1000"

    volumes:
      - .:/automation

    stdin_open: true
    tty: true
  